### ISSUE TITLE
Need API function to get raw configuration

### ISSUE THREAD

**Issue by barrycaceres** [Senzing/senzing-rest-api#28]
Currently no way to access the raw configuration from the REST API -- only data sources and attribute types are available.

Add a new end-point to obtain the raw configuration.

Also need an endpoint for version information.

**Comment by barrycaceres** [comment]
This was completed

**Comment by docktermj** [comment]
Pull requests:

1. https://github.com/Senzing/senzing-rest-api/pull/29
