### ISSUE TITLE
On the `GET /version` endpoint, configCompatibilityVersion should be a string

### ISSUE THREAD

**Issue by barrycaceres** [Senzing/senzing-rest-api#31]
When the `GET /version` endpoint was defined, the `configCompatibilityVersion` field in the result was incorrectly specified as an integer when it should be a version string.

**Comment by barrycaceres** [comment]
Fixed in 1.7.5

**Comment by docktermj** [comment]
Pull requests:

1. https://github.com/Senzing/senzing-rest-api/pull/32
